name: build

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    name: Build & Deploy the Site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.8.0
          cache: 'npm'

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Build
        run: |
          npm ci
          npx hexo generate
          cp -r statics/* public
          tar -czvf public.tar.gz public

      - name: Deploy
        run: |
          scp public.tar.gz ecs-user@liuwj.me:~/public.tar.gz
          ssh ecs-user@liuwj.me "tar -xzvf public.tar.gz && rm -rf /var/www/www.liuwj.me && mv public /var/www/www.liuwj.me && rm public.tar.gz"
